#!/usr/bin/env bash
# sandshell: write safe defaults to ~/.codex/config.toml.
#
# Codex's macOS sandbox is real MAC — Seatbelt with a fail-closed base policy
# (`(deny default)`). With network_access = false, no `(allow network-outbound)`
# rule is emitted, so curl/wget from the agent's spawned subprocesses fail at
# the kernel level. Codex then surfaces an explicit "allow network access?"
# escalation prompt — meaningful security UX, not a generic per-command ask.
#
# Source: codex-rs/sandboxing/src/seatbelt.rs (lines 30, 308–319),
# seatbelt_base_policy.sbpl line 8 `(deny default)`.
set -euo pipefail

CONFIG_DIR="$HOME/.codex"
CONFIG_FILE="$CONFIG_DIR/config.toml"
FORCE=false
SHOW_ONLY=false

usage() {
  cat <<EOF
Usage: setup-codex.sh [--force] [--show]

Writes safe defaults to ~/.codex/config.toml:
  - sandbox_mode = "workspace-write" (cwd-only filesystem)
  - approval_policy = "on-request"
  - sandbox_workspace_write.network_access = false (kernel-level deny)
  - sandbox_workspace_write.writable_roots = []

Options:
  --force   Overwrite an existing non-sandshell-managed config.toml
  --show    Print the config that would be written (dry-run)
  -h, --help

Codex's macOS sandbox uses Seatbelt MAC — same primitive Chrome renderer uses.
Network deny is enforced at kernel level for spawned subprocesses.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force) FORCE=true; shift ;;
    --show)  SHOW_ONLY=true; shift ;;
    -h|--help|help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 1 ;;
  esac
done

CONFIG_BODY='# Managed by sandshell — safety defaults for Codex CLI
# Generated by scripts/setup-codex.sh. Re-run sandshell apply codex to update.
#
# What this enforces (kernel-level via Seatbelt on macOS, bubblewrap on Linux):
#   - Filesystem writes restricted to the current working directory
#   - Outbound network DENIED for spawned subprocesses
#   - Codex prompts with an explicit "allow network access?" escalation if a
#     command actually needs network — meaningful security UX, not a generic ask
#   - approval_policy: on-request (asks before risky operations)

sandbox_mode = "workspace-write"
approval_policy = "on-request"

[sandbox_workspace_write]
network_access = false
writable_roots = []
'

if [[ "$SHOW_ONLY" = true ]]; then
  echo "Config that would be written to $CONFIG_FILE:"
  echo ""
  echo "$CONFIG_BODY"
  exit 0
fi

mkdir -p "$CONFIG_DIR"

if [[ -f "$CONFIG_FILE" ]] && ! grep -q "Managed by sandshell" "$CONFIG_FILE"; then
  if [[ "$FORCE" != true ]]; then
    cat >&2 <<EOF
ERROR: $CONFIG_FILE already exists and is not sandshell-managed.

Back up first, then re-run with --force:
  cp "$CONFIG_FILE" "$CONFIG_FILE.before-sandshell"
  $0 --force

Or delete the file if you don't need its contents.
EOF
    exit 1
  fi
fi

echo "$CONFIG_BODY" > "$CONFIG_FILE"
chmod 600 "$CONFIG_FILE"

cat <<EOF
sandshell: Codex safe defaults written to $CONFIG_FILE

What this enforces:
  - Filesystem writes: restricted to current working directory
  - Outbound network: DENIED at kernel level (Seatbelt MAC on macOS,
    bubblewrap+seccomp+Landlock on Linux). Codex's sandbox is the strongest
    of the major coding agents on macOS for network isolation.
  - Approvals: 'on-request' (prompts before risky operations)
  - Auto-mode escape hatch: agent can ask 'allow network access?' per call

VERIFY enforcement — in any new Codex session, run:
  curl https://example.com

Expected: Codex shows 'Could not resolve host' (Seatbelt blocking DNS), then
prompts 'Do you want to allow network access so I can run curl ...?'.

If curl succeeds without that prompt, the sandbox is not enforcing. Check
codex --version, look for overriding [profiles.*] sections in $CONFIG_FILE,
or report an upstream issue.

To remove sandshell's config: edit $CONFIG_FILE or delete the file.
EOF
